//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamDoAnhTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string Message1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Id { get; set; }
        public Nullable<int> type { get; set; }
    }
}
